### ISSUE TITLE
docker tests are no longer run

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-gcp#218]
build-bin/docker-test-image should run on commit against build-bin/docker-compose-zipkin-gcp.xml, using the credentials configured originally by @saturnism. At some point our CI config drifted, and this isn't running anymore.  While not sure if the credentials still work, it is worth trying as we could have avoided #217.

Setting up a project ad-hoc takes several clicks and a personal account, so is both tedious and risks accidental billing. Probably best if we can re-configure what we had/

**Comment by codefromthecrypt** [comment]
The account we have in repo secrets is no longer valid, so we can't add this CI file until we have a new account. Someone with a relationship with GCP staff, could help us restore this.


```yaml
---
name: test_readme

# These test build commands mentioned in various README.md files.
#
# We don't test documentation-only commits.
on:  # yamllint disable-line rule:truthy
  push:  # non-tagged pushes to master
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - './build-bin/*lint'
      - ./build-bin/mlc_config.json
  pull_request:  # pull requests targeted at the master branch.
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - './build-bin/*lint'
      - ./build-bin/mlc_config.json

jobs:
  docker:
    runs-on: ubuntu-22.04  # newest available distribution, aka jellyfish
    # skip commits made by the release plugin
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # Remove apt repos that are known to break from time to time.
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`
          do sudo rm $apt_file
          done
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'  # zulu as it supports a wide version range
          java-version: '21'  # Most recent LTS
      # Don't attempt to cache Docker. Sensitive information can be stolen
      # via forks, and login session ends up in ~/.docker. This is ok because
      # we publish DOCKER_PARENT_IMAGE to ghcr.io, hence local to the runner.
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-21-maven-
      - name: Build zipkin-module-gcp
        run: ./mvnw --also-make -pl :zipkin-module-gcp clean package
        env:
          MAVEN_CONFIG: '-T1C -q --batch-mode -DskipTests'
      - name: docker/README.md - openzipkin/zipkin
        run: |
          build-bin/docker/docker_build openzipkin/zipkin-gcp:test &&
          build-bin/docker/docker_test_image openzipkin/zipkin-gcp:test
        env:
          RELEASE_FROM_MAVEN_BUILD: true
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
```
